# Generated by Django 5.1.1 on 2024-09-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_passwordresetcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=9),
        ),
        migrations.AddField(
            model_name='user',
            name='type_user',
            field=models.CharField(choices=[('CLIENT', 'cliente'), ('DELIVERY', 'delivery'), ('FOOD_STORE', 'food_store')], default='CLIENT', max_length=15),
        ),
    ]
